import { MigrationInterface, QueryRunner } from "typeorm";

export class CleanRebuild1774133387176 implements MigrationInterface {
    name = 'CleanRebuild1774133387176'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_invoice_items_invoice"`);
        await queryRunner.query(`ALTER TABLE "rate_locks" DROP CONSTRAINT "FK_rate_locks_exchange_rate"`);
        await queryRunner.query(`ALTER TABLE "rate_locks" DROP CONSTRAINT "FK_rate_locks_invoice"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP CONSTRAINT "FK_bank_accounts_user"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_payouts_bank_account"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_payouts_user"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_payouts_transaction"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_exchange_rate"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_user"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_transactions_invoice"`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" DROP CONSTRAINT "FK_wallet_addresses_invoice"`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" DROP CONSTRAINT "FK_wallet_addresses_user"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_rate_lock"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoices_user"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" DROP CONSTRAINT "FK_kyc_records_reviewer"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" DROP CONSTRAINT "FK_kyc_records_user"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_user"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_audit_logs_user"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_referrals_referred"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_referrals_referrer"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_users_referred_by"`);
        await queryRunner.query(`ALTER TABLE "platform_settings" DROP CONSTRAINT "FK_platform_settings_updated_by"`);
        await queryRunner.query(`ALTER TABLE "system_wallet_transactions" DROP CONSTRAINT "fk_swt_wallet"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rate_locks_expires"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_exchange_rates_coin_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bank_accounts_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payouts_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payouts_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payouts_flw_transfer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_invoice"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_tx_hash"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_nowpayments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_transactions_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wallet_addresses_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wallet_addresses_invoice"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoices_nowpayments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_kyc_records_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_read"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_entity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referrals_referrer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_webhook_events_external_ref"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_webhook_events_processed"`);
        await queryRunner.query(`DROP INDEX "public"."idx_swt_wallet_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_swt_type"`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_type_enum" AS ENUM('credit', 'debit', 'transfer_in', 'transfer_out', 'payout', 'reversal')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "wallet_id" uuid NOT NULL, "type" "public"."wallet_transactions_type_enum" NOT NULL, "amount" numeric(18,2) NOT NULL, "balance_before" numeric(18,2) NOT NULL, "balance_after" numeric(18,2) NOT NULL, "reference" character varying(100) NOT NULL, "description" character varying(255) NOT NULL, "counterpart_wallet_id" uuid, "counterpart_tag" character varying(20), "related_payout_id" uuid, "related_transaction_id" uuid, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_4b3d5cb7b4480ca1c3c367ebb45" UNIQUE ("reference"), CONSTRAINT "PK_5120f131bde2cda940ec1a621db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_51d7930b03e5ce28fec21f42dc" ON "wallet_transactions" ("wallet_id", "type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4b3d5cb7b4480ca1c3c367ebb4" ON "wallet_transactions" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_6956721ecd7d2f8bd5a1d99046" ON "wallet_transactions" ("wallet_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."user_wallets_status_enum" AS ENUM('active', 'frozen', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "user_wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "tag" character varying(20) NOT NULL, "balance_ngn" numeric(18,2) NOT NULL DEFAULT '0', "locked_balance_ngn" numeric(18,2) NOT NULL DEFAULT '0', "total_received_ngn" numeric(18,2) NOT NULL DEFAULT '0', "total_sent_ngn" numeric(18,2) NOT NULL DEFAULT '0', "status" "public"."user_wallets_status_enum" NOT NULL DEFAULT 'active', "freeze_reason" text, "frozen_at" TIMESTAMP WITH TIME ZONE, "last_transaction_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7382818ff309cabe40c7a74237a" UNIQUE ("user_id"), CONSTRAINT "UQ_14fcbb7140f1f8249a4958c2114" UNIQUE ("tag"), CONSTRAINT "REL_7382818ff309cabe40c7a74237" UNIQUE ("user_id"), CONSTRAINT "PK_f98089275dcfc65d59b1d347167" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_14fcbb7140f1f8249a4958c211" ON "user_wallets" ("tag") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7382818ff309cabe40c7a74237" ON "user_wallets" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_phone_verified"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "auto_cashout" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "auto_cashout_bank_account_id" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type" RENAME TO "coin_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."rate_locks_coin_enum" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "rate_locks" ALTER COLUMN "coin" TYPE "public"."rate_locks_coin_enum" USING "coin"::"text"::"public"."rate_locks_coin_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coin_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type" RENAME TO "coin_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."exchange_rates_coin_enum" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "coin" TYPE "public"."exchange_rates_coin_enum" USING "coin"::"text"::"public"."exchange_rates_coin_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coin_type_old"`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "spread_percent" SET DEFAULT '1.5'`);
        await queryRunner.query(`ALTER TYPE "public"."rate_source" RENAME TO "rate_source_old"`);
        await queryRunner.query(`CREATE TYPE "public"."exchange_rates_source_enum" AS ENUM('nowpayments', 'coingecko', 'manual')`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "source" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "source" TYPE "public"."exchange_rates_source_enum" USING "source"::"text"::"public"."exchange_rates_source_enum"`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "source" SET DEFAULT 'nowpayments'`);
        await queryRunner.query(`DROP TYPE "public"."rate_source_old"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "transaction_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."payout_status" RENAME TO "payout_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payouts_status_enum" AS ENUM('pending', 'processing', 'success', 'failed', 'reversed')`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "status" TYPE "public"."payouts_status_enum" USING "status"::"text"::"public"."payouts_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payout_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type" RENAME TO "coin_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_coin_enum" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "coin" TYPE "public"."transactions_coin_enum" USING "coin"::"text"::"public"."transactions_coin_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coin_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."network_type" RENAME TO "network_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_network_enum" AS ENUM('bitcoin', 'ethereum', 'solana', 'tron')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "network" TYPE "public"."transactions_network_enum" USING "network"::"text"::"public"."transactions_network_enum"`);
        await queryRunner.query(`DROP TYPE "public"."network_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."transaction_status" RENAME TO "transaction_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('waiting', 'confirming', 'confirmed', 'failed', 'expired', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "status" TYPE "public"."transactions_status_enum" USING "status"::"text"::"public"."transactions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "status" SET DEFAULT 'waiting'`);
        await queryRunner.query(`DROP TYPE "public"."transaction_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type" RENAME TO "coin_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_addresses_coin_enum" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" ALTER COLUMN "coin" TYPE "public"."wallet_addresses_coin_enum" USING "coin"::"text"::"public"."wallet_addresses_coin_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coin_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."network_type" RENAME TO "network_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_addresses_network_enum" AS ENUM('bitcoin', 'ethereum', 'solana', 'tron')`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" ALTER COLUMN "network" TYPE "public"."wallet_addresses_network_enum" USING "network"::"text"::"public"."wallet_addresses_network_enum"`);
        await queryRunner.query(`DROP TYPE "public"."network_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_status" RENAME TO "invoice_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'pending', 'paid', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoices_status_enum" USING "status"::"text"::"public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoice_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type" RENAME TO "coin_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_selected_coin_enum" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "selected_coin" TYPE "public"."invoices_selected_coin_enum" USING "selected_coin"::"text"::"public"."invoices_selected_coin_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coin_type_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "UQ_ffe5c392460e0c6877b9417e922" UNIQUE ("rate_lock_id")`);
        await queryRunner.query(`ALTER TYPE "public"."kyc_status" RENAME TO "kyc_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_records_status_enum" AS ENUM('pending', 'submitted', 'verified', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "status" TYPE "public"."kyc_records_status_enum" USING "status"::"text"::"public"."kyc_records_status_enum"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."kyc_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_type" RENAME TO "notification_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('invoice_paid', 'payout_sent', 'kyc_approved', 'kyc_rejected', 'payment_waiting', 'payment_confirming', 'payout_failed', 'invoice_expired')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notifications_type_enum" USING "type"::"text"::"public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_channel" RENAME TO "notification_channel_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('email', 'sms', 'in_app', 'push')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "channel" TYPE "public"."notifications_channel_enum" USING "channel"::"text"::"public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_channel_old"`);
        await queryRunner.query(`ALTER TYPE "public"."audit_actor_type" RENAME TO "audit_actor_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_actor_type_enum" AS ENUM('user', 'admin', 'system', 'webhook')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "actor_type" TYPE "public"."audit_logs_actor_type_enum" USING "actor_type"::"text"::"public"."audit_logs_actor_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_actor_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."referral_status" RENAME TO "referral_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."referrals_status_enum" AS ENUM('pending', 'qualified', 'rewarded', 'expired')`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" TYPE "public"."referrals_status_enum" USING "status"::"text"::"public"."referrals_status_enum"`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."referral_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin', 'super_admin')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TYPE "public"."kyc_status" RENAME TO "kyc_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_kyc_status_enum" AS ENUM('pending', 'submitted', 'verified', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "kyc_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "kyc_status" TYPE "public"."users_kyc_status_enum" USING "kyc_status"::"text"::"public"."users_kyc_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "kyc_status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."kyc_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."webhook_source" RENAME TO "webhook_source_old"`);
        await queryRunner.query(`CREATE TYPE "public"."webhook_events_source_enum" AS ENUM('nowpayments', 'flutterwave')`);
        await queryRunner.query(`ALTER TABLE "webhook_events" ALTER COLUMN "source" TYPE "public"."webhook_events_source_enum" USING "source"::"text"::"public"."webhook_events_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_source_old"`);
        await queryRunner.query(`ALTER TYPE "public"."system_wallet_tx_type" RENAME TO "system_wallet_tx_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."system_wallet_transactions_type_enum" AS ENUM('credit', 'debit', 'top_up', 'fee_credit', 'payout_reserve', 'reconciliation')`);
        await queryRunner.query(`ALTER TABLE "system_wallet_transactions" ALTER COLUMN "type" TYPE "public"."system_wallet_transactions_type_enum" USING "type"::"text"::"public"."system_wallet_transactions_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."system_wallet_tx_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."system_wallet_status" RENAME TO "system_wallet_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."system_wallets_status_enum" AS ENUM('active', 'maintenance')`);
        await queryRunner.query(`ALTER TABLE "system_wallets" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "system_wallets" ALTER COLUMN "status" TYPE "public"."system_wallets_status_enum" USING "status"::"text"::"public"."system_wallets_status_enum"`);
        await queryRunner.query(`ALTER TABLE "system_wallets" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."system_wallet_status_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_dc991d555664682cfe892eea2c" ON "invoice_items" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa18f735d91eef7013572dcdad" ON "rate_locks" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_18d3598e795f7fef64c5d3b80f" ON "rate_locks" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7acd165e2aaf56eee62cdc884" ON "exchange_rates" ("coin", "fetched_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_29146c4a8026c77c712e01d922" ON "bank_accounts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d9ff7d205bb092404c0f17cd9" ON "payouts" ("flw_transfer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f32ee6d2385d9a8bc0cc92af5" ON "payouts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d4cccb2284ac44a2781a83278" ON "payouts" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_18b1b9fbdcac20fb5447b6d96e" ON "payouts" ("transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_da87c55b3bbbe96c6ed88ea7ee" ON "transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9da81f5f81094ab1d4d780ea14" ON "transactions" ("nowpayments_payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0deaa0ee5092d45fac99139de7" ON "transactions" ("tx_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9acc6efa76de013e8c1553ed2" ON "transactions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a12e9b258f9cd052e43cacf75" ON "transactions" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_413632b2c3de2de42473446368" ON "wallet_addresses" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d52507da26d88286d452e26f7f" ON "wallet_addresses" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_966565d38248dc8680e14b139d" ON "wallet_addresses" ("address") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7570f7ec54710c913014d7be7" ON "invoices" ("nowpayments_invoice_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d8f8d3788694e1b3f96c42c36f" ON "invoices" ("invoice_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_762b27b5024ea45600068f56c0" ON "invoices" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d20b5a5f164a27f1a823596d19" ON "kyc_records" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_310667f935698fcd8cb319113a" ON "notifications" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_af08fad7c04bb85403970afdc1" ON "notifications" ("user_id", "is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c72beecc73a7cc4beb9dd9c183" ON "referrals" ("referral_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_507a2818bf5524662b068c2e81" ON "referrals" ("referred_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_18af9fcaffac6d6d3b28130e14" ON "referrals" ("referrer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ba10055f9ef9690e77cf6445cb" ON "users" ("referral_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c2f5f461ca00d421976e458ff" ON "webhook_events" ("processed") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc6d2f7e8f528774ca19ad6ed7" ON "webhook_events" ("external_ref") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_aa9e65518370e3d7b2e93facf2" ON "webhook_events" ("idempotency_key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5d9031e30fac3ec3ec8b9602e1" ON "platform_settings" ("key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_48d2105f32c3da2264c854e8a7" ON "system_wallet_transactions" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_31e1738c305015eb8d1054354f" ON "system_wallet_transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f954b5b853f85eea9d2c1d905" ON "system_wallet_transactions" ("system_wallet_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_dc991d555664682cfe892eea2c1" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_locks" ADD CONSTRAINT "FK_18d3598e795f7fef64c5d3b80f6" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_locks" ADD CONSTRAINT "FK_4abba5e38b7c6685387a6172b22" FOREIGN KEY ("exchange_rate_id") REFERENCES "exchange_rates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD CONSTRAINT "FK_29146c4a8026c77c712e01d922b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_18b1b9fbdcac20fb5447b6d96e5" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_5d4cccb2284ac44a2781a832786" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_7796c1df57eeefa9173325627c4" FOREIGN KEY ("bank_account_id") REFERENCES "bank_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_3a12e9b258f9cd052e43cacf75b" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_e9acc6efa76de013e8c1553ed2b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_2ddf8097edeba902d22283313e3" FOREIGN KEY ("exchange_rate_id") REFERENCES "exchange_rates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" ADD CONSTRAINT "FK_d52507da26d88286d452e26f7f8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" ADD CONSTRAINT "FK_413632b2c3de2de424734463683" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ffe5c392460e0c6877b9417e922" FOREIGN KEY ("rate_lock_id") REFERENCES "rate_locks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ADD CONSTRAINT "FK_d20b5a5f164a27f1a823596d192" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ADD CONSTRAINT "FK_2d9c43ab127f33c52a665d6fafc" FOREIGN KEY ("reviewed_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_18af9fcaffac6d6d3b28130e149" FOREIGN KEY ("referrer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_507a2818bf5524662b068c2e81c" FOREIGN KEY ("referred_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a78a00605c95ca6737389f6360b" FOREIGN KEY ("referred_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "platform_settings" ADD CONSTRAINT "FK_d78be592623babc45ca60885eff" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_wallet_transactions" ADD CONSTRAINT "FK_be3ca100da24807f27bd0756066" FOREIGN KEY ("system_wallet_id") REFERENCES "system_wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_c57d19129968160f4db28fc8b28" FOREIGN KEY ("wallet_id") REFERENCES "user_wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_wallets" ADD CONSTRAINT "FK_7382818ff309cabe40c7a74237a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_wallets" DROP CONSTRAINT "FK_7382818ff309cabe40c7a74237a"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_c57d19129968160f4db28fc8b28"`);
        await queryRunner.query(`ALTER TABLE "system_wallet_transactions" DROP CONSTRAINT "FK_be3ca100da24807f27bd0756066"`);
        await queryRunner.query(`ALTER TABLE "platform_settings" DROP CONSTRAINT "FK_d78be592623babc45ca60885eff"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a78a00605c95ca6737389f6360b"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_507a2818bf5524662b068c2e81c"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_18af9fcaffac6d6d3b28130e149"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" DROP CONSTRAINT "FK_2d9c43ab127f33c52a665d6fafc"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" DROP CONSTRAINT "FK_d20b5a5f164a27f1a823596d192"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ffe5c392460e0c6877b9417e922"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637"`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" DROP CONSTRAINT "FK_413632b2c3de2de424734463683"`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" DROP CONSTRAINT "FK_d52507da26d88286d452e26f7f8"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_2ddf8097edeba902d22283313e3"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_e9acc6efa76de013e8c1553ed2b"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_3a12e9b258f9cd052e43cacf75b"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_7796c1df57eeefa9173325627c4"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_5d4cccb2284ac44a2781a832786"`);
        await queryRunner.query(`ALTER TABLE "payouts" DROP CONSTRAINT "FK_18b1b9fbdcac20fb5447b6d96e5"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP CONSTRAINT "FK_29146c4a8026c77c712e01d922b"`);
        await queryRunner.query(`ALTER TABLE "rate_locks" DROP CONSTRAINT "FK_4abba5e38b7c6685387a6172b22"`);
        await queryRunner.query(`ALTER TABLE "rate_locks" DROP CONSTRAINT "FK_18d3598e795f7fef64c5d3b80f6"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_dc991d555664682cfe892eea2c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f954b5b853f85eea9d2c1d905"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31e1738c305015eb8d1054354f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48d2105f32c3da2264c854e8a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d9031e30fac3ec3ec8b9602e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa9e65518370e3d7b2e93facf2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc6d2f7e8f528774ca19ad6ed7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c2f5f461ca00d421976e458ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba10055f9ef9690e77cf6445cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18af9fcaffac6d6d3b28130e14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_507a2818bf5524662b068c2e81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c72beecc73a7cc4beb9dd9c183"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af08fad7c04bb85403970afdc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_310667f935698fcd8cb319113a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d20b5a5f164a27f1a823596d19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_762b27b5024ea45600068f56c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8f8d3788694e1b3f96c42c36f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7570f7ec54710c913014d7be7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_966565d38248dc8680e14b139d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d52507da26d88286d452e26f7f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_413632b2c3de2de42473446368"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a12e9b258f9cd052e43cacf75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9acc6efa76de013e8c1553ed2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0deaa0ee5092d45fac99139de7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9da81f5f81094ab1d4d780ea14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da87c55b3bbbe96c6ed88ea7ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18b1b9fbdcac20fb5447b6d96e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d4cccb2284ac44a2781a83278"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f32ee6d2385d9a8bc0cc92af5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d9ff7d205bb092404c0f17cd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29146c4a8026c77c712e01d922"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7acd165e2aaf56eee62cdc884"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18d3598e795f7fef64c5d3b80f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa18f735d91eef7013572dcdad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc991d555664682cfe892eea2c"`);
        await queryRunner.query(`CREATE TYPE "public"."system_wallet_status_old" AS ENUM('active', 'maintenance')`);
        await queryRunner.query(`ALTER TABLE "system_wallets" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "system_wallets" ALTER COLUMN "status" TYPE "public"."system_wallet_status_old" USING "status"::"text"::"public"."system_wallet_status_old"`);
        await queryRunner.query(`ALTER TABLE "system_wallets" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."system_wallets_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."system_wallet_status_old" RENAME TO "system_wallet_status"`);
        await queryRunner.query(`CREATE TYPE "public"."system_wallet_tx_type_old" AS ENUM('credit', 'debit', 'top_up', 'fee_credit', 'payout_reserve', 'reconciliation')`);
        await queryRunner.query(`ALTER TABLE "system_wallet_transactions" ALTER COLUMN "type" TYPE "public"."system_wallet_tx_type_old" USING "type"::"text"::"public"."system_wallet_tx_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."system_wallet_transactions_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."system_wallet_tx_type_old" RENAME TO "system_wallet_tx_type"`);
        await queryRunner.query(`CREATE TYPE "public"."webhook_source_old" AS ENUM('nowpayments', 'flutterwave')`);
        await queryRunner.query(`ALTER TABLE "webhook_events" ALTER COLUMN "source" TYPE "public"."webhook_source_old" USING "source"::"text"::"public"."webhook_source_old"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_events_source_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."webhook_source_old" RENAME TO "webhook_source"`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_status_old" AS ENUM('pending', 'submitted', 'verified', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "kyc_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "kyc_status" TYPE "public"."kyc_status_old" USING "kyc_status"::"text"::"public"."kyc_status_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "kyc_status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."users_kyc_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."kyc_status_old" RENAME TO "kyc_status"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('user', 'admin', 'super_admin')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'user'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`CREATE TYPE "public"."referral_status_old" AS ENUM('pending', 'qualified', 'rewarded', 'expired')`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" TYPE "public"."referral_status_old" USING "status"::"text"::"public"."referral_status_old"`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."referrals_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."referral_status_old" RENAME TO "referral_status"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_actor_type_old" AS ENUM('user', 'admin', 'system', 'webhook')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "actor_type" TYPE "public"."audit_actor_type_old" USING "actor_type"::"text"::"public"."audit_actor_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_actor_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."audit_actor_type_old" RENAME TO "audit_actor_type"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_channel_old" AS ENUM('email', 'sms', 'in_app', 'push')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "channel" TYPE "public"."notification_channel_old" USING "channel"::"text"::"public"."notification_channel_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_channel_old" RENAME TO "notification_channel"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_old" AS ENUM('invoice_paid', 'payout_sent', 'kyc_approved', 'kyc_rejected', 'payment_waiting', 'payment_confirming', 'payout_failed', 'invoice_expired')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notification_type_old" USING "type"::"text"::"public"."notification_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."notification_type_old" RENAME TO "notification_type"`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_status_old" AS ENUM('pending', 'submitted', 'verified', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "status" TYPE "public"."kyc_status_old" USING "status"::"text"::"public"."kyc_status_old"`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."kyc_records_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."kyc_status_old" RENAME TO "kyc_status"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "UQ_ffe5c392460e0c6877b9417e922"`);
        await queryRunner.query(`CREATE TYPE "public"."coin_type_old" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "selected_coin" TYPE "public"."coin_type_old" USING "selected_coin"::"text"::"public"."coin_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_selected_coin_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type_old" RENAME TO "coin_type"`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_status_old" AS ENUM('draft', 'pending', 'paid', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoice_status_old" USING "status"::"text"::"public"."invoice_status_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_status_old" RENAME TO "invoice_status"`);
        await queryRunner.query(`CREATE TYPE "public"."network_type_old" AS ENUM('bitcoin', 'ethereum', 'solana', 'tron')`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" ALTER COLUMN "network" TYPE "public"."network_type_old" USING "network"::"text"::"public"."network_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_addresses_network_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."network_type_old" RENAME TO "network_type"`);
        await queryRunner.query(`CREATE TYPE "public"."coin_type_old" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" ALTER COLUMN "coin" TYPE "public"."coin_type_old" USING "coin"::"text"::"public"."coin_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_addresses_coin_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type_old" RENAME TO "coin_type"`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_status_old" AS ENUM('waiting', 'confirming', 'confirmed', 'failed', 'expired', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "status" TYPE "public"."transaction_status_old" USING "status"::"text"::"public"."transaction_status_old"`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "status" SET DEFAULT 'waiting'`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."transaction_status_old" RENAME TO "transaction_status"`);
        await queryRunner.query(`CREATE TYPE "public"."network_type_old" AS ENUM('bitcoin', 'ethereum', 'solana', 'tron')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "network" TYPE "public"."network_type_old" USING "network"::"text"::"public"."network_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_network_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."network_type_old" RENAME TO "network_type"`);
        await queryRunner.query(`CREATE TYPE "public"."coin_type_old" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "transactions" ALTER COLUMN "coin" TYPE "public"."coin_type_old" USING "coin"::"text"::"public"."coin_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_coin_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type_old" RENAME TO "coin_type"`);
        await queryRunner.query(`CREATE TYPE "public"."payout_status_old" AS ENUM('pending', 'processing', 'success', 'failed', 'reversed')`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "status" TYPE "public"."payout_status_old" USING "status"::"text"::"public"."payout_status_old"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."payouts_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payout_status_old" RENAME TO "payout_status"`);
        await queryRunner.query(`ALTER TABLE "payouts" ALTER COLUMN "transaction_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."rate_source_old" AS ENUM('nowpayments', 'coingecko', 'manual')`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "source" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "source" TYPE "public"."rate_source_old" USING "source"::"text"::"public"."rate_source_old"`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "source" SET DEFAULT 'nowpayments'`);
        await queryRunner.query(`DROP TYPE "public"."exchange_rates_source_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."rate_source_old" RENAME TO "rate_source"`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "spread_percent" SET DEFAULT 1.5`);
        await queryRunner.query(`CREATE TYPE "public"."coin_type_old" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "exchange_rates" ALTER COLUMN "coin" TYPE "public"."coin_type_old" USING "coin"::"text"::"public"."coin_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."exchange_rates_coin_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type_old" RENAME TO "coin_type"`);
        await queryRunner.query(`CREATE TYPE "public"."coin_type_old" AS ENUM('btc', 'eth', 'sol', 'usdt_trc20', 'usdt_erc20')`);
        await queryRunner.query(`ALTER TABLE "rate_locks" ALTER COLUMN "coin" TYPE "public"."coin_type_old" USING "coin"::"text"::"public"."coin_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."rate_locks_coin_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."coin_type_old" RENAME TO "coin_type"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "auto_cashout_bank_account_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "auto_cashout"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_phone_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(20)`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7382818ff309cabe40c7a74237"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14fcbb7140f1f8249a4958c211"`);
        await queryRunner.query(`DROP TABLE "user_wallets"`);
        await queryRunner.query(`DROP TYPE "public"."user_wallets_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6956721ecd7d2f8bd5a1d99046"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b3d5cb7b4480ca1c3c367ebb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51d7930b03e5ce28fec21f42dc"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_type_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_swt_type" ON "system_wallet_transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_swt_wallet_date" ON "system_wallet_transactions" ("system_wallet_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_events_processed" ON "webhook_events" ("processed") `);
        await queryRunner.query(`CREATE INDEX "IDX_webhook_events_external_ref" ON "webhook_events" ("external_ref") `);
        await queryRunner.query(`CREATE INDEX "IDX_referrals_referrer" ON "referrals" ("referrer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_user" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_entity" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_date" ON "notifications" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_read" ON "notifications" ("user_id", "is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_kyc_records_user_id" ON "kyc_records" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_nowpayments" ON "invoices" ("nowpayments_invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoices_user_status" ON "invoices" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_wallet_addresses_invoice" ON "wallet_addresses" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_wallet_addresses_user" ON "wallet_addresses" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_status" ON "transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_nowpayments" ON "transactions" ("nowpayments_payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_tx_hash" ON "transactions" ("tx_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_user" ON "transactions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_transactions_invoice" ON "transactions" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payouts_flw_transfer" ON "payouts" ("flw_transfer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payouts_status" ON "payouts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payouts_user" ON "payouts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bank_accounts_user_id" ON "bank_accounts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_exchange_rates_coin_date" ON "exchange_rates" ("coin", "fetched_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_rate_locks_expires" ON "rate_locks" ("expires_at") `);
        await queryRunner.query(`ALTER TABLE "system_wallet_transactions" ADD CONSTRAINT "fk_swt_wallet" FOREIGN KEY ("system_wallet_id") REFERENCES "system_wallets"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "platform_settings" ADD CONSTRAINT "FK_platform_settings_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_users_referred_by" FOREIGN KEY ("referred_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_referrals_referrer" FOREIGN KEY ("referrer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_referrals_referred" FOREIGN KEY ("referred_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_audit_logs_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ADD CONSTRAINT "FK_kyc_records_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_records" ADD CONSTRAINT "FK_kyc_records_reviewer" FOREIGN KEY ("reviewed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoices_rate_lock" FOREIGN KEY ("rate_lock_id") REFERENCES "rate_locks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" ADD CONSTRAINT "FK_wallet_addresses_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_addresses" ADD CONSTRAINT "FK_wallet_addresses_invoice" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_invoice" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_transactions_exchange_rate" FOREIGN KEY ("exchange_rate_id") REFERENCES "exchange_rates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_payouts_transaction" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_payouts_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payouts" ADD CONSTRAINT "FK_payouts_bank_account" FOREIGN KEY ("bank_account_id") REFERENCES "bank_accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD CONSTRAINT "FK_bank_accounts_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_locks" ADD CONSTRAINT "FK_rate_locks_invoice" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_locks" ADD CONSTRAINT "FK_rate_locks_exchange_rate" FOREIGN KEY ("exchange_rate_id") REFERENCES "exchange_rates"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_invoice_items_invoice" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
